GET http://localhost:5000/users

###
GET http://localhost:5000/users/86ebbe3d-f24a-4fbf-99bf-a17c68123e5c

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username":"beolite",
    "name":"beolite",
    "email":"wwaterr313@gmail.com",
    "password":"icikiwir",
    "confPassword":"icikiwir",
    "role":"user"
}

###
PATCH http://localhost:5000/users/69571d9f-a27c-48f8-ab0e-bfc368c1b5ae
Content-Type: application/json

{
    "username":"ibeol",
    "name":"revanskibidi",
    "email":"sigmasigma@gmail.com",
    "password":"icikiwir",
    "confPassword":"icikiwir",
    "role":"user"
}

###
DELETE http://localhost:5000/users/df4d19e8-d8d1-4dce-ad40-67e6df500ee4

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"wwaterr313@gmail.com",
    "password":"icikiwir"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"sigmasigma@gmail.com",
    "password":"icikiwir"
}


###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout

//post
###
GET http://localhost:5000/post

###
POST http://localhost:5000/post
Content-Type: application/json

{
    "title":"rizz of the skibidi",
    "content":"rizzlord of ohio"
}

###
DELETE http://localhost:5000/post/7b7e4685-9944-4b3d-b930-3481806c3420